project:
  type: website
  output-dir: docs

website:
  title: "Matteo Torres"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true


