project:
  type: website
  output-dir: docs

website:
  title: "Matteo Torres"
  navbar:
    title: matteo
    right:
      - href: index.qmd
        text: home
      - href: about.qmd
        text: about
      - href: resources.qmd
        text: resources
      - href: posts.qmd
        text: blog
      - href: Torres_Matteo_Resume.pdf
        text: resume
        target: _blank
  page-footer:
    left: Copyright 2024, Matteo Torres
    right: This website is built with {{< fa brands github title="The GitHub octocat logo" >}}, {{< fa brands r-project title="R Project" >}}, Quarto, and {{< fa heart title="a heart" >}}

format:
  html:
    theme: 
    - cyborg
    - styles.scss
    mainfont: Arial Narrow
    fontcolor: white
    toc: false
    page-layout: full


